import time

from consts import Tanks, Ranged, Mages, Warriors, Assasins, Supports, Musicians, Brothers


def intro():
    q = ""
    print("██████╗░██╗░░░██╗████████╗███████╗████████╗")
    print("██╔══██╗╚██╗░██╔╝╚══██╔══╝██╔════╝╚══██╔══╝")
    print("██████╔╝░╚████╔╝░░░░██║░░░█████╗░░░░░██║░░░")
    print("██╔═══╝░░░╚██╔╝░░░░░██║░░░██╔══╝░░░░░██║░░░")
    print("██║░░░░░░░░██║░░░░░░██║░░░██║░░░░░░░░██║░░░")
    print("╚═╝░░░░░░░░╚═╝░░░░░░╚═╝░░░╚═╝░░░░░░░░╚═╝░░░")
    print()
    print("Game made by Kolbes.")
    print()

    while q != "start":
        print("Aby zobaczyć podpowiedzi wpisz '1'.")
        print("Aby zobaczyć listę bohaterów wpisz '2'.")
        print("Aby rozpocząć grę wpisz 'start'.")
        q = input("Co chcesz zrobić?: ")
        if q == "1":
            print()
            print("                                              Kupowanie Postaci:")
            print("                   | Ezreal - 1 | Rammus - 2 | Skarner - 1 | Nasus - 2 | Heimer - 1 |")
            print("                                                   ^     ^")
            print("                                                Postać  Cena")
            print("                           | Numer 1 | Numer 2 | Numer 3 | Numer 4 | Numer 5 |")
            print("                          Siła postaci zależy od twojego poziomu doświadczenia.")
            print("                           Im wyższy poziom tym silniejsze postacie w sklepie.")
            time.sleep(5)
            print()
            print("                                                     Arena:")
            print("                                    | Mundo - 1 | Skarner - 1 | Rammus - 2 |")
            print("                                      | Numer 1 | Numer 2 | Numer 3 | itd.")
            print("                      Ilość miejsc na arenie jest zależna od twojego poziomu doświadcznia.")
            print("                      Poziom 1 = 1 miejsce, Poziom 2 = 2 miejsca, ... Poziom 9 = 9 miejsc.")
            time.sleep(5)
            print()
            print("                                                     Ławka:")
            print("                  | Ezreal - 1 | Ashe - 1 | Senna - 2 | Talyiah - 3 | Twitch - 4 |  |  |  |  |")
            print("                                      | Numer 1 | Numer 2 | Numer 3 | itd.")
            print("                              Ławka przez całą rozgrywkę nie zmiennie ma 9 miejsc.")
            time.sleep(5)
            print()
            print("                                                Poziomy Postaci:")
            print("                          1. Każda postać zaczyna pierszym poziomie.")
            print("                          2. Drugi poziom to 3 takie same postaci na poziomie pierwszym.")
            print("                          3. Trzeci poziom to 3 takie same postacie na poziomie drugim.")
            time.sleep(5)
            print()
            print("                                               Ulepszanie Postaci:")
            print("                                   Aby ulepszyć postać musisz posiadać na ławce")
            print("                                   3 takie same postacie na tym samym poziomie.")
            time.sleep(5)
            print()
        elif q == "2":
            print()
            print("Obrońcy:", *Tanks, sep=" | ", end=" |"'\n')
            print()
            print("Strzelcy:", *Ranged, sep=" | ", end=" |"'\n')
            print()
            print("Magowie:", *Mages, sep=" | ", end=" |"'\n')
            print()
            print("Wojownicy:", *Warriors, sep=" | ", end=" |"'\n')
            print()
            print("Zabójcy:", *Assasins, sep=" | ", end=" |"'\n')
            print()
            print("Wspierający:", *Supports, sep=" | ", end=" |"'\n')
            print()
            print("Muzycy:", *Musicians, sep=" | ", end=" |"'\n')
            print()
            print("Bracia :", *Brothers, sep=" | ", end=" |"'\n')
            time.sleep(5)
            print()
        elif q != "start":
            print()
            print("Niewłaściwy argument!!!")
            time.sleep(1)
            print()

